# Soubor:	Makefile
# Datum:	31.3.2024
# Autor:	Bc. Jiri Vaclavic, xvacla31@stud.fit.vutbr.cz
# Projekt:	FLP, Haskell - Rozhodovaci strom
# Popis:	Implementace rozhodovaciho stromu

all:
	ghc src/flp-fun.hs -o flp-fun -Wall

clean:
	rm flp-fun src/flp-fun.o src/flp-fun.hi
